AWSTemplateFormatVersion: "2010-09-09"
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html
Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
  VpcId:
    Type: String
    Default: vpc-c3be22b9
  ImageId:
    Type: String
    # us-east-1 AMI
    Default: ami-04e5276ebb8451442
  SubnetId:
    Type: String
    Default: subnet-d0c28f8c
Resources:
  MyEC2Instance1: 
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: us-east-1a
      IamInstanceProfile: !Ref EC2InstanceProfile
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
  MyEC2Instance2: 
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: us-east-1a
      IamInstanceProfile: !Ref EC2InstanceProfile
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
  SSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SSMRole
  NewVolume:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-volume.html
    Type: AWS::EC2::Volume
    Properties:
      Size: 4
      VolumeType: io2
      Iops: 100
      AvailabilityZone: us-east-1a
      MultiAttachEnabled: true
      Tags:
        - Key: Name
          Value: NewVolume
    DeletionPolicy: Snapshot
  MountPoint1:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-volumeattachment.html
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref MyEC2Instance1
      VolumeId: !Ref NewVolume
      Device: /dev/sdh
  MountPoint2:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-volumeattachment.html
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref MyEC2Instance2
      VolumeId: !Ref NewVolume
      Device: /dev/sdh